export default {
    name: 'Arash Hosseini',
    home: 'HOME',
    about: "ABOUT",
    resume: "RESUME",
    portfolios: "PORTFOLIOS",
    contact: "CONTACT",
    hi: "Hi, I am ",
    hi2: '',
    desc: 'I am a fronted web developer.I can provide clean code and pixel perefect design.I also make website & more intractive with web animations.',
    aboutme: 'ABOUT ME',
    services: 'SERVICES',
    fullname: 'Full name',
    age: 'Age',
    nationality: 'Nationality',
    languages: 'Languages',
    phone: 'Phone',
    years: 'Years',
    iranian: 'Iranian',
    persian: 'Persian',
    english: 'English',
    DownloadCv:'Download Cv'
}